receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug: # コンソールにテレメトリーデータを出力するためdebugを使用
    verbosity: detailed
  nop:
  mackerel_otlp:

service:
  #telemetry:
  #  logs:
  #    level: DEBUG
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [mackerel_otlp]
    traces:
      receivers: [otlp]
      exporters: [mackerel_otlp]
    logs:
      receivers: [otlp]
      exporters: [mackerel_otlp]
